/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeMenuHider */

#ifndef _Included_NativeMenuHider
#define _Included_NativeMenuHider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeMenuHider
 * Method:    hideMenuJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeMenuHider_hideMenuJNI
  (JNIEnv *, jobject);

/*
 * Class:     NativeMenuHider
 * Method:    showMenuJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeMenuHider_showMenuJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
